### ISSUE TITLE
Improve quality score

### ISSUE THREAD

**Issue by NITEMAN** [sbitio/puppet-monit#2]
Fix issues listed in https://forge.puppetlabs.com/sbitio/monit/scores

**Comment by NITEMAN** [comment]
Improvements on f439749, 09235ef, 8bf59ef, 85a41d6, 86280bb

Since 'Optional parameter listed before required parameter' is marked as error and 'ensure found on line but it's not the first attribute' is just marked as warning, I've chosen tu put optional parameters before

**Comment by NITEMAN** [comment]
@jonhattan with 8c61e84 there are only 2 types of puppet-lint warnings standing:
```
WARNING: class not documented on line 1
WARNING: defined type not documented on line 1
WARNING: line has more than 80 characters on line XX
```

I think we can safely bump version number and release to the forge

**Comment by jonhattan** [comment]
Added docs.
