### ISSUE TITLE
Lookup variables in scope from templates -> Sets 'undef' in some environments.

### ISSUE THREAD

**Issue by MNiedzielski** [sbitio/puppet-monit#20]
In our environment, the change to scope results in a configuration where all undefined variables are set as undef in the config files.

Prepending each scope with a test like '! [:undefined, :undef, nil, ''].include?' works for us.  Do you have a preferred fix?

**Comment by jonhattan** [comment]
@MNiedzielski I think my preferred fix is upgrading to 4.x :disappointed:. The change in scope tests was done in #11. As I remember there's no elegant solution that works both for puppet 3.x, 3.x with future parser and 4.x.

**Comment by jonhattan** [comment]
The commit related to #11 is a mess. I'll revert it and provide a release for puppet 3.x and another for 4.x

**Comment by jonhattan** [comment]
Closing because of obsolete.
