### ISSUE TITLE
Checking error in host.pp

### ISSUE THREAD

**Issue by aepgit** [sbitio/puppet-monit#22]
The line host.pp:21 has an error in the if check:
"if !is_domain_name($address) or !is_ip_address($address)"

The "or" should be "and", since now it only passes if the address is both a domain_name AND and ip_address because of the double-negative. 
With an "and" it would check if it's neither a domain_name or an ip_address.

I have the fix ready if you grant me rights for creating a branch/pull request.

**Comment by jonhattan** [comment]
Si I took my time to merge it :smile:. Thanks!
