### ISSUE TITLE
On cetons missing repo epel

### ISSUE THREAD

**Issue by nvtkaszpir** [sbitio/puppet-monit#26]
Looks like epel repo is required on centos to install monit.

this can be fixed by adding module to Puppetfile:
```ruby
mod 'stahnma-epel'
```
and then manifest file can look like this:
```puppet

  include ::epel
  include ::monit

  Class['epel'] -> Class['monit::install'] # cannot do just Class['monit'] because the way module is constructed

```

**Comment by jonhattan** [comment]
How does other modules manage this? PRs welcome!

**Comment by nvtkaszpir** [comment]
AFAIR they usually don't manage repos if they can.
They explicitly describe it in the README of the module that adding repo is out of scope of the module, and the only thing they care is exact package name. 
This way the module user is free to define his own specific class/stages dependencies which can be sometimes quite complicated.

So the PR could look like expanding readme for Debian/Redhat based distros to show how to do it easily just like this issue :)

If you want to really introduce repo management to make it totally hands free experience then you must provide most commonly used modules to manage repos for supported platforms, then add it to metadata as dependency, extend docs and fight with future module updates :)
