### ISSUE TITLE
Concat Requriments

### ISSUE THREAD

**Issue by delhora** [sbitio/puppet-monit#29]
Hello,

I'm having some warnings that concat is not supported (currently it's supported until 3.0.0) but concat is now at version 4.1.1

I've tried so far to update `metadata.json` to `    {"name":"puppetlabs/concat","version_requirement":">= 1.2.1 < 5.0.0"}` and it's seems to work correctly.

It's possible to update metadata.json to accept the new version of concat?

Also a new tag in forge would be so nice like #23 said

Thank you very much

**Comment by jonhattan** [comment]
Done. Sorry for the delay. I'll release a new version once I've reviewed/fixed all the open issues.
