### ISSUE TITLE
 Start and stop program parameters

### ISSUE THREAD

**Issue by wdec** [sbitio/puppet-monit#34]
These two parameters are optional in the monit config, while the current puppet module makes them mandatory.

**Comment by jonhattan** [comment]
Can you please point me to the monit documentation where it states those parameters are optional? I was unable to find it in the manual.

**Comment by wdec** [comment]
The simplest form of usage (1 liner) in the config examples shows this:
https://www.mmonit.com/monit/documentation/monit.html#CONFIGURATION-EXAMPLES.

**Comment by jonhattan** [comment]
Thanks! just implemented it.
