### ISSUE TITLE
Upgrade module to support Puppet4

### ISSUE THREAD

**Issue by wdec** [sbitio/puppet-monit#35]
Various parts for the module need updating to support puppet 4.

**Comment by jonhattan** [comment]
Upgraded to functions API here: https://github.com/sbitio/puppet-monit/commit/08b7ccbde63084f9883cd4fdd19025236ec9ed2a

**Comment by jonhattan** [comment]
I'm using the module with puppet 4 since a long ago. Please create specific issues if you find any bug.
