### ISSUE TITLE
Tag current release, or branch.

### ISSUE THREAD

**Issue by jocado** [sbitio/puppet-monit#36]
It would be very useful if we had a nice ref to include for versioning.
Following master is't a good idea in prod, and had coding commit hashes isn't great either.

Can you maybe create tag for the current state, or even better make a 2.x stable branch or something to follow?

**Comment by jonhattan** [comment]
I'm planning a release once I've reviewed/fixed open issues.

**Comment by jonhattan** [comment]
2.0.0 released
