### ISSUE TITLE
Add support for MATCHING in services (when no PID available)

### ISSUE THREAD

**Issue by NITEMAN** [sbitio/puppet-monit#4]
New monit versions support regex matching of process[1]

~~~
CHECK PROCESS <unique name> <PIDFILE <path> | MATCHING <regex>>
~~~

In some distributions there are services which doesn't generate a proper pidfile (b.e.: ntpd service on Centos 7)

Provide a way to deal with that

[1] https://mmonit.com/monit/documentation/monit.html

**Comment by jonhattan** [comment]
In the meanwhile.. You can still configure the pidfile in /etc/sysconfig/ntpd. For some reason Centos 7 doesn't ship with this option. Perhaps because of the change from sysv to systemd.
